apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name flux-gitops
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-gitops-secret
    template:
      data:
        githubAppID: '{{ .GITHUB_APP_ID }}'
        githubAppInstallationID: '{{ .GITHUB_APP_INSTALLATION_ID }}'
        githubAppPrivateKey: '{{ .GITHUB_APP_PRIVATE_KEY }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: flux-operator
