apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name flux-gitops
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flux-gitops-secret
    template:
      data:
        githubAppID: '{{ .flux_operator_github_app_id }}'
        githubAppInstallationID: '{{ .flux_operator_github_app_installation_id }}'
        githubAppPrivateKey: '{{ .flux_operator_github_app_private_key }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: flux-operator
    rewrite:
    - regexp:
        source: (.*)
        target: flux_operator_$1
