# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name unpackerr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unpackerr-secret
    template:
      data:
        UN_RADARR_0_API_KEY: '{{ .unpackerr_radarr_api_key }}'
        UN_SONARR_0_API_KEY: '{{ .unpackerr_sonarr_api_key }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: unpackerr
    rewrite:
    - regexp:
        source: (.*)
        target: unpackerr_$1
