---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rook-ceph-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/rook/rook.git
  ref:
    # renovate: registryUrl=https://charts.rook.io/release chart=rook-ceph
    tag: v1.12.6
  ignore: |
    # exclude all
    /*
    # path to crds
    !/deploy/examples/crds.yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-crds
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: rook-ceph-source
