---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../flux/components/common
resources:
  - ./audiobookshelf/ks.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./jellyfin/ks.yaml
  - ./seerr/ks.yaml
  - ./kometa/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./tqm/ks.yaml
  - ./unpackerr/ks.yaml
