---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/receiver-notification-v1.json
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-receiver
spec:
  type: github
  events:
    - ping
    - push
  secretRef:
    name: github-webhook-token-secret
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
      namespace: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: flux-system
      namespace: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/receiver-notification-v1.json
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: cookjam-receiver
spec:
  type: github
  events:
    - workflow_run
  secretRef:
    name: github-webhook-token-secret
  resources:
    # Image Repositories
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: cookjam
      namespace: selfhosted
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: cookjam-web-api
      namespace: selfhosted
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: cookjam-web-chat-api
      namespace: selfhosted
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageRepository
      name: cookjam-web-worker
      namespace: selfhosted
    # Image Policies
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImagePolicy
      name: cookjam
      namespace: selfhosted
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImagePolicy
      name: cookjam-web-api
      namespace: selfhosted
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImagePolicy
      name: cookjam-web-chat-api
      namespace: selfhosted
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImagePolicy
      name: cookjam-web-worker
      namespace: selfhosted
    # Image Update Automation
    - apiVersion: image.toolkit.fluxcd.io/v1
      kind: ImageUpdateAutomation
      name: cookjam-gitops
      namespace: selfhosted
