---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname "external.${SECRET_DOMAIN}"
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
      lbipam.cilium.io/ips: "10.20.69.128"
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "*.${SECRET_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "${SECRET_DOMAIN/./-}-production-tls"
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
    - name: https-app
      port: 443
      protocol: HTTPS
      hostname: "${SECRET_APP_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "${SECRET_APP_DOMAIN/./-}-production-tls"
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
    - name: https-app-wildcard
      port: 443
      protocol: HTTPS
      hostname: "*.${SECRET_APP_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "${SECRET_APP_DOMAIN/./-}-production-tls"
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
    - name: https-app-prd
      port: 443
      protocol: HTTPS
      hostname: "${SECRET_APP_PRD_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "${SECRET_APP_PRD_DOMAIN/./-}-production-tls"
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
    - name: https-app-prd-wildcard
      port: 443
      protocol: HTTPS
      hostname: "*.${SECRET_APP_PRD_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "${SECRET_APP_PRD_DOMAIN/./-}-production-tls"
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
