apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name clickhouse
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: clickhouse-secret
    template:
      data:
        CLICKHOUSE_PASSWORD: '{{ .CLICKHOUSE_PASSWORD }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: clickhouse-operator
