apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name radicale
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template: {}
  data:
  - secretKey: users
    remoteRef:
      key: radicale
      property: users
  dataFrom:
  - extract:
      key: radicale
