---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cookjam-reg
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GITHUB_USERNAME }}",
                "password": "{{ .GITHUB_TOKEN }}",
                "auth": "{{ printf "%s:%s" .GITHUB_USERNAME .GITHUB_TOKEN | b64enc }}"
              }
            }
          }
  dataFrom:
  - extract:
      key: cookjam
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cookjam
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cookjam-secret
    template:
      data:
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        # Supabase
        SUPABASE_JWT_SECRET: "{{ .SUPABASE_JWT_SECRET }}"
        SUPABASE_PROJECT_ID: "{{ .SUPABASE_PROJECT_ID }}"
        SUPABASE_URL: "{{ .SUPABASE_URL }}"
        SUPABASE_SERVICE_ROLE_KEY: "{{ .SUPABASE_SERVICE_ROLE_KEY }}"
        DATABASE_URL: "{{ .DATABASE_URL }}"
        # Chat
        LANGFUSE_SECRET_KEY: "{{ .LANGFUSE_SECRET_KEY }}"
        LANGFUSE_PUBLIC_KEY: "{{ .LANGFUSE_PUBLIC_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: cookjam_dev
        INIT_POSTGRES_HOST: postgres-cookjam-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cookjam
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cookjam-refresh-api-key
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cookjam-refresh-api-key
    template:
      data:
        SUPABASE_PROJECT_ID: "{{ .SUPABASE_PROJECT_ID }}"
        REFRESH_STATS_API_KEY: "{{ .REFRESH_STATS_API_KEY }}"
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cookjam
