---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &name cookjam
spec:
  provider:
    doppler:
      project: *name
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cookjam-reg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cookjam
  target:
    name: *name
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GITHUB_USERNAME }}",
                "password": "{{ .GITHUB_TOKEN }}",
                "auth": "{{ printf "%s:%s" .GITHUB_USERNAME .GITHUB_TOKEN | b64enc }}"
              }
            }
          }
  dataFrom:
    - find:
        name:
          regexp: .*
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cookjam
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cookjam
  target:
    name: cookjam-secret
    template:
      engineVersion: v2
      data:
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        # Supabase
        SUPABASE_JWT_SECRET: "{{ .SUPABASE_JWT_SECRET }}"
        SUPABASE_PROJECT_ID: "{{ .SUPABASE_PROJECT_ID }}"
        SUPABASE_URL: "{{ .SUPABASE_URL }}"
        SUPABASE_SERVICE_KEY: "{{ .SUPABASE_SERVICE_KEY }}"
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-cookjam-pooler.database.svc.cluster.local:5432/cookjam_dev"
        # Chat
        LANGFUSE_SECRET_KEY: "{{ .LANGFUSE_SECRET_KEY }}"
        LANGFUSE_PUBLIC_KEY: "{{ .LANGFUSE_PUBLIC_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: cookjam_dev
        INIT_POSTGRES_HOST: postgres-cookjam-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - find:
        name:
          regexp: .*
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cookjam-refresh-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cookjam
  target:
    name: cookjam-refresh-api-key
    template:
      engineVersion: v2
      data:
        SUPABASE_PROJECT_ID: "{{ .SUPABASE_PROJECT_ID }}"
        REFRESH_STATS_API_KEY: "{{ .REFRESH_STATS_API_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: .*
