apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-dns
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-dns-secret
    template:
      data:
        CF_API_TOKEN: '{{ .cloudflare_dns_cloudflare_dns_token }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cloudflare-dns
    rewrite:
    - regexp:
        source: (.*)
        target: cloudflare_dns_$1
