apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: dex-k8s-authenticator-helm-values
  namespace: kube-system
spec:
  keys:
    - values.yaml
  path: secrets/kube-system/dex/dex-k8s-authenticator-helm-values
  type: Opaque
