---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - object-bucket-claim.yaml
namespace: monitoring
configMapGenerator:
  - name: loki-alerting-rules
    files:
      - ./rules/loki-alerting-rules.yaml
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
