---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-external
spec:
  hostnames:
    - "grafana.${SECRET_APP_DOMAIN}"
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /public-dashboards
      backendRefs:
        - name: grafana
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /api/public
      backendRefs:
        - name: grafana
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /api/plugins
      backendRefs:
        - name: grafana
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /public
      backendRefs:
        - name: grafana
          port: 80
