---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  interval: 1h
  chart:
    spec:
      chart: tuppr
      version: 0.0.75
      sourceRef:
        kind: HelmRepository
        name: home-operations
        namespace: flux-system
  values:
    replicaCount: 2
    monitoring:
      serviceMonitor:
        enabled: true
