---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: si-discord
              href: https://discord.com
    - Git:
        - home-ops:
            - icon: si-github
              href: https://github.com/rust84/k8s-gitops
    - Media:
        - YouTube:
            - icon: si-youtube
              href: https://youtube.com/feed/subscriptions
    - Reading:
        - Hacker News:
            - icon: si-ycombinator
              href: https://news.ycombinator.com/
        - Tildes:
            - icon: mdi-forum
              href: https://tildes.net/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  services.yaml: |
    - Downloads:
        - qBittorrent:
            icon: qbittorrent.png
            href: https://qbittorrent.${SECRET_DOMAIN}
            description: Torrents
            widget:
              type: qbittorrent
              url: http://qbittorrent.media.svc.cluster.local:8080
    - Home:
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.${SECRET_DOMAIN}
            description: Status page
            widget:
              type: uptimekuma
              url: https://uptime.roswellian.dev
              slug: "{{HOMEPAGE_VAR_UPTIMEKUMA_SLUG}}"
  settings.yaml: |
    title: Russell
    headerStyle: clean
    layout:
      Media:
        style: row
        columns: 4
      Downloads:
        style: row
        columns: 2
      Home:
        style: row
        columns: 2
      AI:
        style: row
        columns: 2
      Selfhosted:
        style: row
        columns: 4
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: short
          timeStyle: short
          hour12: false
    - search:
        provider: custom
        url: https://search.${SECRET_DOMAIN}/search?q=
        target: _blank
    - openmeteo:
        label: Home
        latitude: "{{HOMEPAGE_VAR_HASS_LATITUDE}}"
        longitude: "{{HOMEPAGE_VAR_HASS_LONGITUDE}}"
        units: metric
        cache: 5
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: false
