---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: si-discord
              href: https://discord.com
    - Git:
        - home-ops:
            - icon: si-github
              href: https://github.com/rust84/k8s-gitops
    - Media:
        - YouTube:
            - icon: si-youtube
              href: https://youtube.com/feed/subscriptions
    - Reading:
        - Hacker News:
            - icon: si-ycombinator
              href: https://news.ycombinator.com/
        - Tildes:
            - icon: mdi-forum
              href: https://tildes.net/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  services.yaml: |
    - Home:
        - Uptime:
            icon: mdi-arrow-up-bold
            href: https://uptime.roswellian.dev/status/home-cluster
            description: Status page
  settings.yaml: |
    title: Russell
    headerStyle: clean
    layout:
      Media:
        style: row
        columns: 4
      Home:
        style: row
        columns: 3
      AI:
        style: row
        columns: 2
      Selfhosted:
        style: row
        columns: 4
  widgets.yaml: |
    - search:
        provider: custom
        url: https://search.${SECRET_DOMAIN}/search?q=
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: false
