# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cookjam-prd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: "ghcr.io/san-vibe-coding-2025/cookjam-web-otp-working"
              tag: "main"
            env:
              VITE_INFERENCE_SERVICE_URL: https://${SECRET_APP_PRD_DOMAIN}/api
              NODE_ENV: production
              METRICS_PORT: 3001
              SUPABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: &secret cookjam-secret
                    key: SUPABASE_URL
              SUPABASE_SERVICE_ROLE_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: SUPABASE_SERVICE_ROLE_KEY
            securityContext: &sc
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
                add: ["CHOWN"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 300Mi
      ml:
        replicas: 2
        strategy: RollingUpdate
        rollingUpdate:
          unavailable: "90%"
        containers:
          frontend:
            image:
              repository: ghcr.io/san-vibe-coding-2025/cookjam-web-inference-api-api
              tag: latest
            env:
              API_PORT: *port
              CACHE_DIR: &cache /cache
              REDIS_URL: &redis redis://dragonfly.database.svc.cluster.local:6379/5
              SUPABASE_JWT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: &secret cookjam-secret
                    key: SUPABASE_JWT_SECRET
              SUPABASE_PROJECT_ID:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: SUPABASE_PROJECT_ID
            securityContext: *sc
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
              limits:
                memory: 200Mi
          worker:
            image:
              repository: ghcr.io/san-vibe-coding-2025/cookjam-web-inference-api-worker
              tag: latest
            env:
              CACHE_DIR: *cache
              DEBUG: 1
              HEALTH_PORT: 8001
              OPENAI_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: OPENAI_API_KEY
              REDIS_URL: *redis
            securityContext: *sc
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &metrics 8001
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 1Gi
              limits:
                memory: 2Gi
    defaultPodOptions:
      imagePullSecrets:
        - name: cookjam-reg
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 568
        runAsGroup: *uid
        fsGroup: *uid
        supplementalGroups: [65534]
        fsGroupChangePolicy: Always
    service:
      app:
        controller: app
        ports:
          http:
            port: *port
      ml:
        controller: ml
        ports:
          http:
            port: *port
          metrics:
            port: *metrics
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_APP_DOMAIN}" # Match cloudflared origin cert
        className: external
        hosts:
          - host: &host "${SECRET_APP_PRD_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
              - path: /api
                service:
                  identifier: ml
                  port: http
        tls:
          - secretName: cookjam-prd.tls
            hosts:
              - *host
    persistence:
      config:
        enabled: false
        existingClaim: *app
      cache:
        type: emptyDir
        advancedMounts:
          app:
            main:
              - path: /var/cache/nginx
              - path: /var/log/nginx
              - path: /var/run
      ml-cache:
        existingClaim: cookjam-nfs
        advancedMounts:
          ml:
            frontend:
              - path: *cache
            worker:
              - path: *cache
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/san-vibe-coding-2025/cookjam-web-otp-working
            newTag: main
            digest: sha256:3832e00d0dce636bfad488ba1f8a010ba464471af361388e0cb4d4f5caa1077c # {"$imagepolicy": "selfhosted:cookjam-prd:digest"}
          - name: ghcr.io/san-vibe-coding-2025/cookjam-web-inference-api-api
            newTag: latest
            digest: sha256:01bac33570640d0bc2e8dee7c1b3620661bd5b7f351c58516c70ac104ad2a5ca # {"$imagepolicy": "selfhosted:cookjam-web-api:digest"}
          - name: ghcr.io/san-vibe-coding-2025/cookjam-web-inference-api-worker
            newTag: latest
            digest: sha256:601b80d9f28c810826e9c941ffdf673439a01946a05a4099a28dd502f39a023e # {"$imagepolicy": "selfhosted:cookjam-web-worker:digest"}
