# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name plex-image-cleanup
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plex-image-cleanup-secret
    template:
      data:
        PLEX_TOKEN: '{{ .PLEX_TOKEN }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: plex
