---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./altinity.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./home-operations.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./stevehipwell.yaml