apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name unifi-dns
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi-dns-secret
    template:
      data:
        api-key: '{{ .UNIFI_API_KEY }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: unifi-dns
