---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qui-secret
    creationPolicy: Owner
    template:
      data:
        QUI__SESSION_SECRET: "{{ .SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: qui