---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: blakeshome-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://blakeblackshear.github.io/blakeshome-charts/
  timeout: 3m
