apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik
  namespace: selfhosted
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        # App
        AUTHENTIK_EMAIL__HOST: '{{ .authentik_authentik_email__host }}'
        AUTHENTIK_EMAIL__USERNAME: '{{ .authentik_authentik_email__username }}'
        AUTHENTIK_EMAIL__PASSWORD: '{{ .authentik_authentik_email__password }}'
        AUTHENTIK_EMAIL__FROM: '{{ .authentik_authentik_email__from }}'
        AUTHENTIK_POSTGRESQL__NAME: &dbName authentik
        AUTHENTIK_POSTGRESQL__HOST: &dbHost "postgres-rw.database.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__USER: '{{ .authentik_authentik_postgresql__user }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: '{{ .authentik_authentik_postgresql__password }}'
        AUTHENTIK_SECRET_KEY: '{{ .authentik_authentik_secret_key }}'
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: '{{ .authentik_authentik_postgresql__user }}'
        INIT_POSTGRES_PASS: '{{ .authentik_authentik_postgresql__password }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .authentik_postgres_super_pass }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: authentik
    rewrite:
    - regexp:
        source: (.*)
        target: authentik_$1
