apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik
  namespace: selfhosted
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authentik-secret
    template:
      data:
        # App
        EMAIL__HOST: '{{ .EMAIL__HOST }}'
        EMAIL__USERNAME: '{{ .EMAIL__USERNAME }}'
        EMAIL__PASSWORD: '{{ .EMAIL__PASSWORD }}'
        EMAIL__FROM: '{{ .EMAIL__FROM }}'
        POSTGRESQL__NAME: &dbName authentik
        POSTGRESQL__HOST: &dbHost "postgres-rw.database.svc.cluster.local"
        POSTGRESQL__USER: '{{ .POSTGRESQL__USER }}'
        POSTGRESQL__PASSWORD: '{{ .POSTGRESQL__PASSWORD }}'
        SECRET_KEY: '{{ .SECRET_KEY }}'
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: '{{ .POSTGRESQL__USER }}'
        INIT_POSTGRES_PASS: '{{ .POSTGRESQL__PASSWORD }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: authentik
  - extract:
      key: cloudnative-pg-superuser
