apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name langfuse
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: langfuse-secret
    template:
      data:
        # Core Authentication Secrets
        NEXTAUTH_SECRET: '{{ .langfuse_nextauth_secret }}'
        SALT: '{{ .langfuse_salt }}'
        ENCRYPTION_KEY: '{{ .langfuse_encryption_key }}'
        DATABASE_URL: '{{ .langfuse_langfuse_postgres_user }}'
        CLICKHOUSE_PASSWORD: '{{ .langfuse_clickhouse_password }}'
        CLICKHOUSE_MIGRATION_URL: '{{ .langfuse_clickhouse_password }}'
        INIT_POSTGRES_DBNAME: langfuse
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: '{{ .langfuse_langfuse_postgres_user }}'
        INIT_POSTGRES_PASS: '{{ .langfuse_langfuse_postgres_pass }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .langfuse_postgres_super_pass }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: langfuse
    rewrite:
    - regexp:
        source: (.*)
        target: langfuse_$1
