apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name langfuse
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: langfuse-secret
    template:
      data:
        # Core Authentication Secrets
        NEXTAUTH_SECRET: '{{ .NEXTAUTH_SECRET }}'
        SALT: '{{ .SALT }}'
        ENCRYPTION_KEY: '{{ .ENCRYPTION_KEY }}'
        DATABASE_URL: '{{ .POSTGRES_USER }}'
        CLICKHOUSE_PASSWORD: '{{ .CLICKHOUSE_PASSWORD }}'
        CLICKHOUSE_MIGRATION_URL: '{{ .CLICKHOUSE_PASSWORD }}'
        INIT_POSTGRES_DBNAME: langfuse
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: '{{ .POSTGRES_USER }}'
        INIT_POSTGRES_PASS: '{{ .POSTGRES_PASS }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: langfuse
  - extract:
      key: cloudnative-pg-superuser
