---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: searxng-configmap
    files:
      - ./resources/limiter.toml
      - ./resources/settings.yml
      - ./resources/hostnames-remove.yml
      - ./resources/hostnames-high.yml
      - ./resources/hostnames-low.yml
generatorOptions:
  disableNameSuffixHash: true
