---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rook-crds
  namespace: rook-ceph
resources:
  - https://raw.githubusercontent.com/rook/rook/v1.7.5/cluster/examples/kubernetes/ceph/crds.yaml
