---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: a63fe352-e482-d8b5-81a3-1c697a00fb0f
spec:
  accepted: true
  hostname: node-0.russhome.xyz
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/network/hostname
      value: node-0.russhome.xyz
  cpu:
    manufacturer: Intel(R) Corporation
    version: Intel(R) Core(TM) i3-8109U CPU @ 3.00GHz
  pxeBootAlways: true
  system:
    family: Intel NUC
    manufacturer: Intel(R) Client Systems
    productName: NUC8i3BEH
    serialNumber: G6BE916003RW
    skuNumber: BOXNUC8i3BEH
    version: J72753-304
