---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - collab.yaml
  - database.yaml
  - default.yaml
  - flux-system.yaml
  - games.yaml
  - home.yaml
  - kasten-io.yaml
  - kube-system.yaml
  - kyverno.yaml
  - media.yaml
  - monitoring.yaml
  - network.yaml
  - rook-ceph.yaml
  - security.yaml
