apiVersion: v1
data:
    config.yaml: ENC[AES256_GCM,data:SDpR,iv:Fr0I6GmHqAXNz41iWeazXWGhmUDnRB2cFlhn+QPMpjM=,tag:sYKO/omOaR0cuYsdj/5S3g==,type:str]
clients:
    qb:
        create_tags_upfront: false
        download_path: /media/downloads/torrents/complete
        enabled: true
        filter: default
        type: qbittorrent
        url: http://qbittorrent.media.svc.cluster.local:8080
filters:
    default:
        MapHardlinksFor:
            - retag
        ignore:
            - IsTrackerDown()
            - Downloaded == false && !IsUnregistered()
            - SeedingHours < 26 && !IsUnregistered()
        remove:
            - IsUnregistered()
            - ( HasAnyTag( "site:ant", "site:ar", "site:fl", "site:fnp", "site:hdt", "site:ipt", "site:me", "site:oe", "site:phd", "site:ptp", "site:td", "site:tl", "site:uhd" ) && (Ratio >= 1.01 || SeedingDays >= 14.1) )
            - ( HasAnyTag("site:ath", "site:blu", "site:mtv", "site:nbl", "site:sp") && SeedingDays >= 14.1 )
            - HasAnyTag("not-linked") && SeedingDays > 24
        tag:
            - name: activity:1d
              update:
                - LastActivityDays < 7
            - name: activity:7d
              update:
                - LastActivityDays >= 7 && LastActivityDays < 14
            - name: activity:14d
              update:
                - LastActivityDays >= 14 && LastActivityDays < 30
            - name: activity:30d
              update:
                - LastActivityDays >= 30 && LastActivityDays < 180
            - name: activity:180d
              update:
                - LastActivityDays >= 180
            - name: added:1d
              update:
                - AddedDays < 7
            - name: added:7d
              update:
                - AddedDays >= 7 && AddedDays < 14
            - name: added:14d
              update:
                - AddedDays >= 14 && AddedDays < 30
            - name: added:30d
              update:
                - AddedDays >= 30 && AddedDays < 180
            - name: added:180d
              update:
                - AddedDays >= 180
            - name: not-linked
              update:
                - HardlinkedOutsideClient == false && Label in ["sonarr", "radarr"]
            - name: site:ant
              update:
                - TrackerName == "anthelion.me"
            - name: site:ar
              update:
                - TrackerName == "alpharatio.cc"
            - name: site:ath
              update:
                - TrackerName == "aither.cc"
            - name: site:bhd
              update:
                - TrackerName == "beyond-hd.me"
            - name: site:blu
              update:
                - TrackerName in ["blutopia.cc", "blutopia.xyz"]
            - name: site:fl
              update:
                - TrackerName in ["filelist.io", "thefl.org"]
            - name: site:fnp
              update:
                - TrackerName == "fearnopeer.com"
            - name: site:gg
              update:
                - TrackerName == "gazellegames.net"
            - name: site:hdt
              update:
                - TrackerName == "hdts-announce.ru"
            - name: site:huno
              update:
                - TrackerName == "hawke.uno"
            - name: site:ipt
              update:
                - TrackerName in ["bgp.technology", "empirehost.me", "stackoverflow.tech"]
            - name: site:lst
              update:
                - TrackerName == "lst.gg"
            - name: site:mam
              update:
                - TrackerName == "myanonamouse.net"
            - name: site:me
              update:
                - TrackerName == "milkie.cc"
            - name: site:mtv
              update:
                - TrackerName == "morethantv.me"
            - name: site:nbl
              update:
                - TrackerName == "nebulance.io"
            - name: site:oe
              update:
                - TrackerName == "onlyencodes.cc"
            - name: site:or
              update:
                - TrackerName == "opsfet.ch"
            - name: site:otw
              update:
                - TrackerName == "oldtoons.world"
            - name: site:phd
              update:
                - TrackerName == "privatehd.to"
            - name: site:ptp
              update:
                - TrackerName == "passthepopcorn.me"
            - name: site:red
              update:
                - TrackerName in ["redacted.sh", "flacsfor.me"]
            - name: site:sp
              update:
                - TrackerName == "seedpool.org"
            - name: site:st
              update:
                - TrackerName == "scenetime.com"
            - name: site:td
              update:
                - TrackerName in ["jumbohostpro.eu", "td-peers.com"]
            - name: site:tl
              update:
                - TrackerName in ["tleechreload.org", "torrentleech.org"]
            - name: site:uhd
              update:
                - TrackerName == "uhdbits.org"
            - name: site:ulcx
              update:
                - TrackerName == "upload.cx"
            - name: tracker-down
              update:
                - IsTrackerDown()
            - name: unregistered
              update:
                - IsUnregistered()
kind: Secret
metadata:
    creationTimestamp: null
    name: tqm-secret
    namespace: media
sops:
    age:
        - recipient: age1wv9mlcm5q92z8q26m85ry3yhgfmzh4cptqeveudxh3nj5jm2dfcqfelgux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSFo5UFI3dnN4c2d2MU4x
            S0UyemlHODRaeEs3QWdUKzgzU0UyR2Q5SjMwClZPN3c1U2VuV1E4WllCQVJQSmM0
            dXdGbUpyRUVxMkNNTFlFY0kyai85a0kKLS0tIG1MU2tSaUhLWU8yUmx3WXBkWnh0
            eXQ0dTd6ZzVaSnR0QXIzaUJKaEFyUHMKTxEb4oVIRslrP1mrZVb5gnXCP4cHQrH2
            eFWspWOh5LBltDST/L2uwBxEwO0lKDlysrg6MJ8HMHzsKeraI8bA2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T02:11:41Z"
    mac: ENC[AES256_GCM,data:5fU8qbyoPhz9+E1WoVIlWO39eclt3uhfh2qE2Gb9GwBR4yjFwNSAkacmhJ8Zge4B7xSoqLWlcJl4JAzAjHkAyPGVFrgIllhs4x4xE3Sx2rsJsxsNrzYwRPDU8lTnudIZBXNDw8yPhSZd67Rkc/y8zKxXXWonh0EIR/UEnngO7Fw=,iv:0MTZR7t0nUSeftq8JFJW5RxXFh7WEfkkbfCbNneoOYo=,tag:ZHPiREW+Fkigd8DX1YtafA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
