apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # App
        WEBUI_SECRET_KEY: '{{ .open_webui_openwebui_secret_key }}'
        DATABASE_NAME: &dbName openwebui
        DATABASE_HOST: &dbHost postgres-rw.database.svc.cluster.local
        DATABASE_USER: '{{ .open_webui_openwebui_db_user }}'
        DATABASE_PASSWORD: '{{ .open_webui_openwebui_db_password }}'
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: '{{ .open_webui_openwebui_db_user }}'
        INIT_POSTGRES_PASS: '{{ .open_webui_openwebui_db_password }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .open_webui_postgres_super_pass }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: open-webui
    rewrite:
    - regexp:
        source: (.*)
        target: open_webui_$1
