---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../flux/components/common
resources:
  - ./cloudflare-dns/ks.yaml
  - ./cloudflared/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./multus/ks.yaml
  - ./unifi-dns/ks.yaml
